### ISSUE TITLE
请问一直重定向是什么原因

### ISSUE THREAD

**Issue by ihaichao** [alibaba/f2etest#105]
![image](https://user-images.githubusercontent.com/8586268/72069972-5f105800-3323-11ea-9dbf-a6cb12198fe1.png)

![image](https://user-images.githubusercontent.com/8586268/72069953-4d2eb500-3323-11ea-92b1-9ce359881d08.png)

![image](https://user-images.githubusercontent.com/8586268/72070010-78b19f80-3323-11ea-9536-96eef4cbf32b.png)

**Comment by undead25** [comment]
钉钉群号：11779932。

**Comment by undead25** [comment]
pull 最新的镜像，已修复。

**Comment by CNzhou-gq** [comment]
我也遇到这样的情况，pm2 stop 0 ，pm2 start 0。好像restart不行的

**Comment by CNzhou-gq** [comment]
应该是conf/server的地址初始化不了
