### ISSUE TITLE
访问 http://127.0.0.1/setuser.asp?username=test&password=hello123&key=f2etest，输出set user fail

### ISSUE THREAD

**Issue by WangYuJiee** [alibaba/f2etest#109]
不知道失败的原因

net framework4 安装了，其他的步骤也重新走了一边，还是没有输出 OK 

之前在win10上这一步是成功的，现在切到2008R2的环境，在这一步反而是走不下去了，求助  是什么原因导致的失败

**Comment by WangYuJiee** [comment]
找到了安全性日志，发现新建用户之后，会跟着一条，安全性的全局组中删除某个成员的日志。  防火墙和前面的IE ESC增强型都已经关闭了，但是还是不成功

**Comment by undead25** [comment]
钉钉群：30684524，截图排查起来更方便一点。

**Comment by CNzhou-gq** [comment]
我也出现错误了，不知道那步错误了
