### ISSUE TITLE
一个新手的问题

### ISSUE THREAD

**Issue by hjonwy** [alibaba/f2etest#11]
配置f2etest-web时，修改conf/site.json：
clientApiKey: f2etest远程桌面客户端的ApiKey，这个值是随便设置的吗？
guacamoleApi: guacamole的API， 是一个什么样的值，能不能给下具体的值

**Comment by yaniswang** [comment]
clientApiKey随便设个随机值就行，只要这个值不会被别人猜出就行
guacamoleApi就是guacamole那个应用部署后可以访问的URL，类似：
http://f2etest-link.xxxx.com/guacamole/client.xhtml

**Comment by shamoyouhun** [comment]
@hjonwy   你好，搭建成功了？
