### ISSUE TITLE
打开应用后（hostshare，浏览器等）不能与本地共享剪切板

### ISSUE THREAD

**Issue by xiaojinniu** [alibaba/f2etest#111]
1.如何解决不能与本地共享剪切板？
2.如果或环境测试，host切换有没有其他快捷方案，而不是每次都要粘贴一遍，类似swithHosts？
谢谢

**Comment by undead25** [comment]
1. 共享剪切板的功能依赖 guacamole，希望升级后能有此功能，目前是支持本机到远程机器，不支持远程机器到本机。
2. 新版本采用的是代理模式，应该能解决你的这个问题。
