### ISSUE TITLE
f2etest-web用docker部署后访问浏览器时无法上网

### ISSUE THREAD

**Issue by Nuoky** [alibaba/f2etest#112]
问题描述：f2etest-web用docker部署后访问浏览器时无法上网，需要取消IE代理后可以上网
问题定位：getHosts.pac接口获取的本地IP是Docker容器环境下的IP

**Comment by Nuoky** [comment]
加上 --network host 后正常，不清楚有没有其它影响
```
docker run --network host -dit --privileged -p 80:80 -p 4444:4444 --name f2etest registry.cn-hangzhou.aliyuncs.com/f2etest/f2etest-web
```

**Comment by undead25** [comment]
下个版本采用代理模式，不再使用 host 模式，当前版本可以通过关闭win机器上的IE代理解决
