### ISSUE TITLE
win10上可以实现点击浏览器图标直接打开页面吗

### ISSUE THREAD

**Issue by hywang87** [alibaba/f2etest#113]
我想在win10上配置浏览器，然后我参考https://developer.aliyun.com/article/712080这个链接里的步骤配置了IE应用，但是打开的是桌面app模式的。
win10上能否实现点击浏览器图标直接打开页面吗？

**Comment by undead25** [comment]
不行，因为WIN 10 不是服务器系统，不支持 RemoteApp 功能。f2etest 直接打开页面依赖 RemoteApp 功能。
