### ISSUE TITLE
不够简单粗暴

### ISSUE THREAD

**Issue by huyinghuan** [alibaba/f2etest#13]
人家就喜欢简单粗暴嘛．．．

主要限制过多

1. 比如对接用户认证．在小的公司可能根本就没有这方面的需求，毕竟只是内网测试兼容性使用

2. 客户度部署困难．　对于不习惯windows的人太j8蛋疼了...iis部署总是没办法访问到．．．我去看了大概客户度就是创建用户之类的操作，和配置浏览器路径．我觉得可以简单粗暴一点，直接在客户端新建特定（规定死)的用户，和配置应用就够了．至于多用户统计之类的可以做成该系统扩展．

guacamole这块配置比较简单还能接受．我公司是 hunantv.com ,对兼容性测试需求比较大，对这个系统其实很需要的，但是奈何我水平过低．．搞不定．．囧了．．

**Comment by yaniswang** [comment]
windows的配置真的没办法了，能做的可能只能是把教程写的更详细点。
做成工具自动化配置，可能难度比较大。

**Comment by wvv8oo** [comment]
@yaniswang 对接用户认证这个功能不是可选咩
@huyinghuan 大芒果怎么能是小公司呢，快提个pr过来，要相信自己嘛。和薛老板说一下，把这套在芒果搞起来

**Comment by yaniswang** [comment]
正在考虑增加一个匿名模式，用户每次访问时生成一个临时用户，并存在在cookie中。

**Comment by yaniswang** [comment]
改为默认使用内置的匿名SSO：https://github.com/alibaba/f2etest/commit/e0a777787335c5b1b80b154536a842a53f5563ca
