### ISSUE TITLE
windows 端安装

### ISSUE THREAD

**Issue by arthur657834** [alibaba/f2etest#14]
windows server 2008 这边是怎么安装的，谁有记录安装过程的，能否分享一下

**Comment by XiaoxiangLi** [comment]
Windows 2008R2 Standard 虚机安装：
	按照前面配置的主机 id 修改主机名，如 f2etest-ie8；激活操作系统。
	虚机配置：
		运行 gpedit.msc
			[计算机配置/管理模板/系统]，右侧的 [显示“关闭事件跟踪程序”] 设为禁用
			[计算机配置/Windows 设置/安全设置/账户策略/密码策略]，禁用 [密码必须符合复杂性要求]、将 [密码最长使用期限] 设为 0
		运行 gpupdate /force
		[控制面板 / 电源选项 / 更改计划设置 / 关闭显示器] 设为 [从不]。
	管理工具 / 服务器管理器 / 添加功能：
		Telnet 客户端、桌面体验（主要是要 Windows Defender）
		然后打开 控制面板 / Windows Defender，更新后自动设置成实时保护。
		弊端：内存消耗增加。
	管理工具 / 服务器管理器 / 添加角色：
		远程桌面服务：
			角色服务：远程桌面会话主机、远程桌面授权
			身份验证方法：不需要使用网络级别身份认证
			授权模式：每用户
			用户组：添加 Authenticated Users
		Web 服务器（IIS）：
			角色服务：勾选上 [应用程序开发/ASP]
		安装完后重启并完成配置。
	管理工具 / 服务器管理器
		配置 IE ESC，禁用
	激活远程桌面授权：
		管理工具 / 远程桌面服务 / 远程桌面授权管理器，在打红叉的服务器上右键/激活服务器
			公司信息：随便填
			许可证安装向导：
				许可证计划：企业协议
				协议号码：6565792
				产品版本：“Windows Server 2008或Windows Server 2008 R2”
				许可证类型：“TS或RDS每用户CAL”
				数量：输入你想允许的最大远程连接数量，如100
			激活后，红叉变绿。
	管理工具 / 远程桌面服务 / 远程桌面会话主机配置：
		双击连接，“会话” 选择5分钟“结束已断开的会话”，“空闲会话限制”设为6小时；“客户端设置/限制最大颜色深度”为15位（提升性能，官方文档说24位）。
			管理员不要5分钟断开吧 -- 没法单独设置，干脆设为2天、4天。
		编辑设置/授权/授权服务器，添加许可证服务器为自己。
	安装 curl：
		http://curl.haxx.se/download.html#Win64，下载 Win64 x86_64 CAB
		解压后，将 AMD64 文件夹下的文件复制到 C:\Windows 文件夹下。
		或者将 f2etest-client/curl 下的 exe 和 dll 文件复制进去。
	安装周边软件：Flash等
		访问 https://get2.adobe.com/cn/flashplayer 安装flash
	更改系统更新设置：
		不允许自动安装更新。
	
在 Win 上部署 f2etest-client
	将 app 文件夹复制到 c 盘根目录下（配置在前面的 app.json 中的），bat文件中需要修改两处地方。
		代理服务器pac地址：修改为hostsShare服务所在的Ip地址
			find -name '*.bat' -exec echo \"{}\" \; | xargs perl -pi -e 's|f2etest.xxxx.com:4000|192.168.0.23:4000|g'
			find -name '*.bat' -exec echo \"{}\" \; | xargs perl -pi -e 's|f2etest.xxx.com:4000|192.168.0.23:4000|g'
		最后一行修改为当前服务的部署域名，用来统计用户的应用使用情况
			find -name '*.bat' -exec echo \"{}\" \; | xargs perl -pi -e 's|f2etest.xxxx.com|192.168.0.23:3000|g'
		将需要的 bat 配置到 [管理工具/远程桌面服务/Remote App] 中：
			如果是2008操作系统，添加时请选择：允许任何命令行参数
	部署 www 下的 setuser.asp
		复制到 c:\interpub\wwwroot 下，并修改：
			apiKey 为前面 conf/site.json 中配置的 clientApiKey。
		[管理工具 / IIS 管理器]，点开 [网站 / Default Web Site]，点击 [身份验证]，右键编辑，[特定用户] IUSR 修改为 Administrator 并输入密码。
			否则 setuser.asp 无法正确执行（没有权限创建用户或修改密码）
		防火墙高级设置：
			将 HTTP 服务的作用域限制仅有 192.168.0.23 可以访问。
		设置 wwwroot 文件夹的权限，拒绝普通用户的所有权限。
			f2etest-client的www目录必需要设置为仅管理员有权限，否则任何人都可以查看到setuser.asp中的apiKey，会有严重的安全风险。
			没有一个合适的组包含普通用户、但不包含admin，因此在系统中新增一个组 F2eTest，并且修改 setuser.asp，将用户添加到组中：
				Set oGroup=oSystem.GetObject("Group","F2eTest")
				oGroup.Add ("winnt://"&username)

在 Win 上部署 hostsShare-client
	将 hostsShare-client 下的 build 文件夹命名为 hostsShare，放到服务器 f2etest-ie11（app.json中配置的） 的 C 盘根目录下。
	将 C:\app\hostsshare.bat 添加到 [管理工具/远程桌面服务/Remote App] 中，并允许任何命令行参数。

下载 IE 并安装（或者通过操作系统自动更新来安装）
	http://windows.microsoft.com/zh-cn/internet-explorer/ie-9-worldwide-languages  --> IE9-Windows7-x64-chs.exe
	http://windows.microsoft.com/zh-cn/internet-explorer/ie-11-worldwide-languages --> IE11-Windows6.1-x64-zh-cn.exe
	IE 10 的官网找不到，可以从其他地方下载 --> IE10-Windows6.1-x64-zh-cn.exe
	注意去掉IE的 关于 菜单中的 “自动安装新版本”！！

**Comment by arthur657834** [comment]
hostsshare.bat  这个文件没有找到，f2etest-client的部署只是将app放到C盘下就可以了吗？

**Comment by arthur657834** [comment]
192.168.0.23是centos的地址吗？

**Comment by yaniswang** [comment]
楼主的教程应该是旧的，新版本，已经没有独立的hostsshare了，已经合并到f2etest-web中

**Comment by arthur657834** [comment]
那现在怎么弄的？

**Comment by yaniswang** [comment]
@arthur657834 新的版本中，hostsShare已经不需要单独部署了

**Comment by zdragon11** [comment]
@XiaoxiangLi  方便加下qq指导下吗  我全部配置了 但是出不来远程界面

**Comment by zdragon11** [comment]
@XiaoxiangLi 方便加下qq指导下吗 我全部配置了 但是出不来远程界面 1337169247

**Comment by arthur657834** [comment]
![1](https://cloud.githubusercontent.com/assets/9419700/11870009/fb638d24-a4fe-11e5-844c-3052e79cf52e.png)
这个错误有谁知道是什么原因，怎么修改

**Comment by yaniswang** [comment]
用户组配置：请将Authenticated Users添加到Remote Desktop Users，允许普通用户可以登录远程

这个步骤，你没有严格按照教程进行配置。

**Comment by arthur657834** [comment]
app.json 中的配置项 "program": "c:\\app\\ie8.bat"  
其中的c:\\app\\ie8.bat 是哪里来的？

**Comment by yaniswang** [comment]
是服务器上的浏览器快捷方式路径。

是在f2etest-client中的

**Comment by arthur657834** [comment]
![1](https://cloud.githubusercontent.com/assets/9419700/11921485/bbda3572-a7c4-11e5-8fa3-fb6c6e7b3471.png)

这个是什么引起的，/f2etest-client/app/下的文件我已经都添加到remote app下了

**Comment by yaniswang** [comment]
![image](https://cloud.githubusercontent.com/assets/970390/11921536/a88c52ce-a7c5-11e5-96e0-cb78484a73d5.png)

**Comment by arthur657834** [comment]
重启一下就能用了-_-!

**Comment by simonguo** [comment]
windows 2003 怎么配置啊？

**Comment by yaniswang** [comment]
2003和2008配置方式一样，具体IIS的差异，网上搜下。

**Comment by leolovenet** [comment]
win2008 下面， IE8 每次都弹出请设置IE的窗口禁用办法，运行中输入gpedit.msc
然后找到用户配置→管理模板→windows components（或者是windows组件）→internet xeplorer
在它的右边框中找到“阻止执行首次运行自定义设置”，并双击它
在打开的新窗口中“已启用”打钩
在下面的“选择您的选择”框中选择“直接转到主页”
确定

**Comment by ariesliu** [comment]
http://blog.csdn.net/wpyily/article/details/50563815
有需要的可以看看我的帖子，在作者的基础上做了一些记录

**Comment by arthur657834** [comment]
3Q,各位
