### ISSUE TITLE
单点系统可用CAS

### ISSUE THREAD

**Issue by shamoyouhun** [alibaba/f2etest#15]
这几天弄别的没登录，推荐个开源的单点系统,，部署比较简单
http://developer.jasig.org/cas/

**Comment by shamoyouhun** [comment]
windows的已经有人贡献了啊。我windows iis加用户权限始终搞不定  走了弯路自已写了个简单jsp的程序弄的

**Comment by yaniswang** [comment]
看来大家都在头痛SSO的问题，我这几天修改下SSO.js，增加个匿名功能

**Comment by yaniswang** [comment]
改为默认使用内置的匿名SSO：https://github.com/alibaba/f2etest/commit/e0a777787335c5b1b80b154536a842a53f5563ca
