### ISSUE TITLE
已经可以登录首页，但例如点击IE8浏览器找不到连接。

### ISSUE THREAD

**Issue by xxmmll** [alibaba/f2etest#18]
还是不太明白怎样使用f2etest,能不能举个例子，怎样去用这个方案的？

**Comment by xxmmll** [comment]
也不能注销用户。

**Comment by xxmmll** [comment]
怎样才算搭建好？

**Comment by xxmmll** [comment]
站点我部署在linux系统下，然后client放在sever2008，对应IE8，登录站点后，点击IE8找不到连接了，是这样使用的吗？

**Comment by yaniswang** [comment]
不能注销是正常的，因为你使用的是默认的匿名SSO

IE8链接打不开，说明你f2etest-guacamole服务没部署正确

**Comment by xxmmll** [comment]
etc/guacamole/noauth-config.xml,该文件只是修改对应的IP地址吗，还要改其它参数吗？

**Comment by xxmmll** [comment]
guacamoleApi: guacamole的API，请修改为上面第3步安装完成的API。
----请问以上的API是在安装guacamole哪里生成的，还是要自己设置的？

**Comment by terminatorheart** [comment]
@xxmmll ，这里的guacamole API值只用修改下ip地址，这里ip地址是修改为ip+前面部署的tomcat端口地址形式，比如你的ip为192.168.1.1,tomcat默认是8080端口，然后就可以写成192.168.1.1:8080

**Comment by xxmmll** [comment]
请问这个文件夹‘guacamole-client-0.9.3’应该怎样部署？

**Comment by terminatorheart** [comment]
@xxmmll 不用部署，拷贝.war文件到tomcat服务器目录下

**Comment by xxmmll** [comment]
安装guacamole没发现什么问题，但就是访问不了/guacamole/client.xhtml

**Comment by xxmmll** [comment]
不知道是不是8080端口问题

**Comment by terminatorheart** [comment]
看看guacd服务和tomcat服务的状态是否正常，这两个服务正常就可以直接访问到guacamole的页面，这里按照教程步骤走是没有问题的，并且也跟windows是否配置没什么关系

**Comment by xxmmll** [comment]
guacd服务和tomcat服务能启动，但就是访问不了。

**Comment by xxmmll** [comment]
终于连上guacamole，但打开对应的IE8，出现提示：An internal error has occurred within the Guacamole server, and the connection has been terminated. If the problem persists, please notify your system administrator, or check your system logs.

**Comment by xxmmll** [comment]
@terminatorheart ‘http://192.168.1.1:8080/guacamole/index.xhtml
能够看到一个包含浏览器选项的页面，并且点击能够打开一个windows登录页面，则说明windows端也部署好了（我部署方式是使用匿名sso的）--------需要登录吗？’

**Comment by xxmmll** [comment]
@terminatorheart   我也进到登录页面了，但后面改怎么用？

**Comment by terminatorheart** [comment]
修改好f2etest-web/conf目录下的site.json，app.json，server.json文件，对应修改下/etc/guacamole/noauth-config.xml文件，然后启动node服务，默认端口是3000,然后就可以访问到了，匿名sso应该无法避免每次点击浏览器图标都要进入windows登录界面

**Comment by yaniswang** [comment]
打开显示登录界面，说明f2etest-client没有正确部署，账号没有正确同步到windows机器上

**Comment by terminatorheart** [comment]
@yaniswang 使用匿名sso情况下也是能同步账号的吗？但是我看到在页面上账户是随机生成的呀，这个账户显然不具有windows系统登录权限的。还是说需要额外去创建一个账户？这里不太理解，请指教

**Comment by terminatorheart** [comment]
@yaniswang 补充疑问，在使用匿名sso前提下，setuser.asp脚本需要在什么时候执行？

**Comment by yaniswang** [comment]
初次访问的时候，会弹出一个窗口，显示正在初始化远程账号

**Comment by terminatorheart** [comment]
@yaniswang 哦，这个过程已经经过了的，在mysql数据库的appUser表中能看到生成的随机用户，我碰到的疑问是在使用匿名sso的前提下，点击浏览器图标是无法直接调用远程windows机器上的应用吧？因为windows机器需要用户名密码登录，还是说直接把随机生成的这个用户添加到远端windows机器上去，用户密码也是要用生成这个用户的时候一起生成的密码？

**Comment by terminatorheart** [comment]
@yaniswang 多谢您的帮助，已经试验过了，是要添加随机生成的用户到windows机器上。唉，看来还是要部署一个sso服务才好

**Comment by yaniswang** [comment]
SSO服务只是生成用户名，密码是初始化时自动生成的，并会同步到所有的windows客户端

**Comment by xxmmll** [comment]
执行app.js发现这个错误提示：Caught exception:  [TypeError: Cannot read property 'ret' of undefined]，请问会有影响的吗？

**Comment by yaniswang** [comment]
有没有更详细的错误信息？

有错误肯定不行。

**Comment by xxmmll** [comment]
file:///usr/share/doc/HTML/index.html，打开guacamole访问不了，请问知道是怎么回事吗?

**Comment by yaniswang** [comment]
当然访问不了，远程中怎么访问你本地的机器？
要想访问你本机的机器，请查看下帮助页面，里面有介绍。

需要你本机开80服务，然后访问你本机的IP。

**Comment by xxmmll** [comment]
我是输入IP地址访问的，但显示“-

The requested URL /guacamole/client.xhtml was not found on this server.

**Comment by yaniswang** [comment]
你的guacamole服务部署正确了吗？

**Comment by xxmmll** [comment]
怎样才算正确部署呢，已经按步骤去做了，也启动成功了，但就是访问不了。

**Comment by yaniswang** [comment]
你说启动成功了，但是为什么访问不了呢？

是不是忘了加端口号？

**Comment by xxmmll** [comment]
我用80可以访问tomcat

**Comment by xxmmll** [comment]
再加上/guacamole/client.xhtml就访问不了了。

**Comment by xxmmll** [comment]
我这里用8080访问不了，输入80就可以，显示Test 123页面。

**Comment by yaniswang** [comment]
cp guacamole-0.9.3.war /usr/local/tomcat7/webapps/guacamole.war
这个命令你执行了吗？

**Comment by xxmmll** [comment]
执行了，但我发现tomcat7里没有解压，我从var里解压的guacamole文件夹复制过去，打开http://xxxxx/guacamole/client.xhtml发现可以进到guacamole初始页面，不知道这样可行吗，初始一直显示，不知道是不是不成功呢

**Comment by xxmmll** [comment]
为什么usr装的是tomcat7，在var里显示的是tomcat,查了下进程，有tomcat和tomcat7。

**Comment by yaniswang** [comment]
你系统里之前是不是已经安装过tomcat了？

**Comment by xxmmll** [comment]
f2etest-client->app->自动代理.bat里的 ‘ set f2etestDomain=f2etest.xxx.com’，需要修改吗，作用是什么？

**Comment by yaniswang** [comment]
f2etest-web有个重要功能就是实现hosts代理，正确配置了这个代理，hosts绑定才能生效。

**Comment by xxmmll** [comment]
访问http://10.0.0.x:8080/guacamole/client.xhtml出现以下：
HTTP Status 404 - /guacamole/index.xhtml

type Status report

message /guacamole/index.xhtml

description The requested resource is not available.

**Comment by xxmmll** [comment]
Connection Error
An internal error has occurred within the Guacamole server, and the connection has been terminated. If the problem persists, please notify your system administrator, or check your system logs.

**Comment by xxmmll** [comment]
@terminatorheart  请问你是怎样添加随机生成的用户到windows机器上的，密码需要设置吗？

**Comment by xxmmll** [comment]
@terminatorheart  我点击IE进入guacamole主页面，提示Connection Error
An internal error has occurred within the Guacamole server, and the connection has been terminated. If the problem persists, please notify your system administrator, or check your system logs.

**Comment by terminatorheart** [comment]
@xxmmll 随机生成的用户应该是根据用户硬件，浏览器等信息生成，在你访问配置的f2etest-web站点首页的时候，右上角有一个install链接，点开是个页面，页面底部有生成的匿名用户的用户名密码，加入到远端windows的用户并给予远程登录权限，就可以直接访问了

**Comment by xxmmll** [comment]
@terminatorheart 请问bat模板你一般是选哪个，f2etest-client怎样才算部署成功呢，有什么打开连接的吗？

**Comment by xxmmll** [comment]
/guacamole/client.xhtml?id=c%2Ff2etest-ie8 进入远程页面后提示用户名和密码不正确，请问该怎么设置？

**Comment by terminatorheart** [comment]
@xxmmll bat模板那里我还没调成功，不大明白。远程页面提示用户名密码不正确很正常，因为你安装windows server的时候设置了用户名与密码，但是现在你去那里访问的时候，使用的是随机生成的用户名与密码，当然会提示用户名密码不正确咯，可以考虑昨天我说的那样，把这个随机生成的用户名密码加入到windows server的用户组中并给予远程登录权限，但是我没看过源码，不清楚在什么情况下会重新生成随机用户，我使用台式机，一般都不关机，目前还没发现重新生成用户名的情况

**Comment by xxmmll** [comment]
@terminatorheart 关机后会重新生成用户名，用随机生成的密码加到远程机里加不上，跟密码的设置机制不一样，只能自己重设一个密码了。我现在用的是自动代理模板，桌面模板不行。

**Comment by terminatorheart** [comment]
@xxmmll 那个有人讲过了，关闭密码验证规则，参见[#14](https://github.com/alibaba/f2etest/issues/14)

**Comment by terminatorheart** [comment]
@xxmmll 关机会重新生成用户名的话就没有好办法了，还是得部署sso服务才行

**Comment by xxmmll** [comment]
@terminatorheart SSO服务怎么部署的，你有部署成功吗？

**Comment by terminatorheart** [comment]
@xxmmll 没有哇，我呆的小小公司，没得这类服务，准备最近着手部署一个

**Comment by xxmmll** [comment]
@terminatorheart 部署好能不能教教俺呀？

**Comment by terminatorheart** [comment]
@xxmmll 互相探讨吧，我之前也没部署过

**Comment by xxmmll** [comment]
@terminatorheart 好，想问下你是做什么职位的？

**Comment by terminatorheart** [comment]
@xxmmll 主要还是前端开发

**Comment by xxmmll** [comment]
@terminatorheart  现在我这里登录IE可以自动进入了，不用输入用户名和密码，也不用将用户密码在远程机上创建了。

**Comment by yaniswang** [comment]
密码同步的过程，是用户首次访问时自动进行的。
因此，对于用户初始化后，你再增加的机器，就需要人肉同步一次账号。

http://f2etest.xxx.com//syncAllRemoteUsers

**Comment by xxmmll** [comment]
不知道是不是我执行了一次http://f2etest.xxx.com//syncAllRemoteUsers，所以就可以自动登录了。

**Comment by xxmmll** [comment]
为什么使用IE时，不时都断开，提示：
Disconnected
You have been disconnected. Reload the page to reconnect

有什么时间设定的吗

**Comment by yaniswang** [comment]
你是不是太时间不动？
教程中设置了超过一定时间不动，会被踢出来。

**Comment by xxmmll** [comment]
时间也太短了吧，觉得一分钟不到就断了

**Comment by terminatorheart** [comment]
@xxmmll 是我哪里弄错了，应该是不需要手动添加用户进去的，我查看了同步用户的脚本，这一步是自动添加用户进去的。

**Comment by terminatorheart** [comment]
@xxmmll 添加用户到windows server是在我们执行同步用户脚本的时候调用对应windows server上配置的setuser.asp脚本完成的，不需要手动添加，我肯定是windows server上面配置有点儿问题，导致setuser脚本没执行起

**Comment by xxmmll** [comment]
@terminatorheart 你要执行下这个http://f2etest.xxx.com/syncAllRemoteUsers，我测过了，我是执行了这个之后就不用添加用户密码了。

**Comment by xxmmll** [comment]
@terminatorheart 这个URL是用来同步所有账号，当你添加了新的机器就要执行一次。

**Comment by yaniswang** [comment]
http://f2etest.xxx.com/syncAllRemoteUsers
是用来，中途增加服务器做同步用的。

普通用户首次访问的时候，会自动调用setuser.asp来进行初始化账号。

**Comment by yaniswang** [comment]
http://f2etest.xxx.com/syncAllRemoteUsers
是用来，中途增加服务器做同步用的。

普通用户首次访问的时候，会自动调用setuser.asp来进行初始化账号。

**Comment by qianlx** [comment]
我昨天刚发现这个应用尝试入手了一下，设置的差不多了，然后也能点击浏览器的图标，就是点结果后一直显示Connected to Guacamole. Waiting for response...，新人求解救，还有@yaniswang 那个qq群加了没人同意进去啊

**Comment by qianlx** [comment]
@yaniswang

**Comment by Stngle** [comment]
安装部署文档参考：
https://alibaba.github.io/f2etest/build/#/artist/f2etest/f2etest-web-install
