### ISSUE TITLE
部署完成访问问题

### ISSUE THREAD

**Issue by terminatorheart** [alibaba/f2etest#19]
我已经部署完成，在部署了f2etest-web的机器上能访问正确的f2etest页面，但是在同一ip组内的其他机器上不能访问到这个页面，而机器之间是可以ping通的，可能是什么问题呢

**Comment by terminatorheart** [comment]
是我自己服务器防火墙配置问题，太愚蠢了。。。

**Comment by simonguo** [comment]
你能不能出一份帮助文档啊？
