### ISSUE TITLE
建议提供docker的方式安装

### ISSUE THREAD

**Issue by limichange** [alibaba/f2etest#2]

**Comment by yaniswang** [comment]
docker之前没接触过，你能提供技术支持吗？

**Comment by ystyle** [comment]
http://yeasy.gitbooks.io/docker_practice/content/

**Comment by xuzhitong89** [comment]
我可以提供docker 的技术方面的帮助

**Comment by yaniswang** [comment]
@xuzhitong89 请教一下，docker是否要求软件要完全黑盒封装起来？对外以参数配置进行工作？

**Comment by xuzhitong89** [comment]
是的 ，我们这里可以给你制作一个包含1，2组件CentOs镜像，但是Windows就不支持了。

**Comment by Stngle** [comment]
linux模块已提供docker，参考

https://github.com/alibaba/f2etest/issues/3
