### ISSUE TITLE
用户名密码错误

### ISSUE THREAD

**Issue by simonguo** [alibaba/f2etest#21]
点击IE图标进入虚机的时候，提示用户名密码错。 
能具体说明一下用户同步整个流程是怎么样的的吗？

需要具体怎么设置，Windows的设置能不能描述详细一些。

**Comment by yaniswang** [comment]
那说明你的f2etest-client没有正确部署，导致两边的用户名和密码不同步。
你先到目标windows server服务器上确认下，对应的用户是否已经创建成功？

**Comment by simonguo** [comment]
搞定了，我已经把IE8 配置好，今天一直用没发现什么问题，上周有时候会出现链接不上的情况，总是断掉，不知道是什么情况。

接下来我把其他浏览器的client安装好

**Comment by yaniswang** [comment]
恭喜！
