### ISSUE TITLE
windows 2003 怎么配置啊？

### ISSUE THREAD

**Issue by simonguo** [alibaba/f2etest#22]
我的访问 setuser.asp 一直返回 set user failed , 到底是哪里配置有问题啊？

**Comment by yaniswang** [comment]
你iis站点没设置为以administrator用户访问吧？

**Comment by simonguo** [comment]
setuser.asp 访问可以了。  通过访问  http:/127.0.0.1/setuser.asp?username=test&password=hello123&key=1452163801632     也可以把test 用户添加进去
但是通过访问 ：http://10.8.8.26:3000/syncAllRemoteUsers  不能把用户同步过去

**Comment by yaniswang** [comment]
key两边不一致吧？

**Comment by simonguo** [comment]
一个是 site.json中的 "clientApiKey":"1452163801632",
一个是 setuser.asp 中的 apiKey = "1452163801632" 

两边都一致的

**Comment by simonguo** [comment]
我通过本地直接访问 http://10.8.8.20/setuser.asp?username=test6&password=hello123&key=1452163801632   也是可以把test6 用户同步到 10.8.8.20 这台机器

**Comment by simonguo** [comment]
https://github.com/alibaba/f2etest/blob/master/f2etest-web/control/syncAllRemoteUsers.js#L39 是通过这里同步的吧

**Comment by simonguo** [comment]
最后 我怀疑我f2etest-web 配置可能有问题， 然后找，发现 https://github.com/alibaba/f2etest/blob/master/f2etest-web/conf/server.json 
这个文件中，我当是只设置了 ie8 浏览器客户端的IP

然后我把
 {
        "id": "f2etest-ie6",
        "ip": "10.8.8.20",
        "remoteApp": false
 }
添加到配置中就OK了
搞定 ， Windows 2003 和 2008 都可以了，接下来就是体力活，把其他浏览器配置好。

**Comment by yaniswang** [comment]
恭喜！

**Comment by ariesliu** [comment]
http://blog.csdn.net/wpyily/article/details/50563815
有需要的可以看看我的帖子，在作者的基础上做了一些记录

**Comment by zhangjianpinghik** [comment]
@simonguo windows端配置求指导，我目前也是访问 setuser.asp 一直返回 set user failed，一直卡在这里了

**Comment by simonguo** [comment]
iis的administrator用户权限你设置了吗？@zhangjianpinghik
