### ISSUE TITLE
360chrome.bat  ,360se.bat  这些配置文件怎么写？

### ISSUE THREAD

**Issue by simonguo** [alibaba/f2etest#23]
我把 360chrome，360se都安装的IE8浏览器服务器上面的，  
360chrome.bat  ,360se.bat 这个两个文件也配置了，路径也修改过了
RomoteApp 中也添加程序了，但是还是不行，

一进入系统，就自动断开了，想问一下 360chrome.bat  ,360se.bat  的配置文件应该怎么写，要注意些什么？

**Comment by ariesliu** [comment]
替换安装路径试一下，不要放到系统用户目录下面

**Comment by sjqryan** [comment]
解决360进入系统后自动断开：给浏览器安装目录Authenticated Users权限

**Comment by fly10000** [comment]
猎豹浏览器出现这个问题，用ariseliu和sjqryan的方法解决了。但是360浏览器依然不行。打开后会显示浏览器，然后自动断掉连接。

**Comment by yaniswang** [comment]
1. 360由于使用了chrome内核，因此必需安装在2003操作系统上，否则会出现崩溃
2. 程序不要安装在当前用户的路径下，安装到根目录下，例如：c:/360/
3.  使用`app/特殊应用/360se.bat`

**Comment by samxupeiran** [comment]
> 猎豹浏览器出现这个问题，用ariseliu和sjqryan的方法解决了。但是360浏览器依然不行。打开后会显示浏览器，然后自动断掉连接。

请问猎豹浏览器具体是怎么解决的呢，感谢～
