### ISSUE TITLE
tutorial 太简单了

### ISSUE THREAD

**Issue by catalsdevelop** [alibaba/f2etest#24]
之前我都是kvm上部署机器，现在打算把kvm和这个东西连起来，发现教程太简单了，搞了一天没有搞定。希望再精炼下教程。还有就是可以用一些小点的依赖么

**Comment by yaniswang** [comment]
可以具体点吗？哪些教程写的不够详细？

**Comment by catalsdevelop** [comment]
我现在从f2etest-web开始部署，就感觉有点复杂了，而且，还需要在windows server上部署iis和asp脚本。
直接在windows server上开启telnet，用管理员登陆来添加、删除用户是不是更方便一些，这样省去了iis和asp这一块。还有sso.js这个东西，这属于定制化的东西吧，我觉得可以作为附加功能。还有一个，就是client端，如果是想直接以app的方式或者只让用户跑浏览器程序，可以只用rdp文件，通过mstsc命令指定rdp文件的一些参数，来实现，这样连guacamole都省了，自己搞一个非常简单的站点，就能维护一组服务器。而且看起来更精简，部署也更简单一些。现在提供的一些功能，可以作为plus功能，做成可选的。

**Comment by yaniswang** [comment]
guacamole是用来提供WEB方式访问浏览器用的，RDP方式我们也有提供，在帮助中有写。
