### ISSUE TITLE
WebDriver云中的浏览器点击打开guacamole后无法登陆。

### ISSUE THREAD

**Issue by dail** [alibaba/f2etest#25]
此处好像有两个问题：
1. 点开的链接中，id的值为ip，在浏览器云中，此处的值时配置在guacamole中的/etc/guacamole/noauth-config.xml中的name。  我临时的解决方案是，将这些IP也配置一遍。
2. 通过第一步，可以登陆进去，但是远程执行的脚本路径错误！ 在部署文档中是将webdriver的文件部署到c:\f2etest-webdriver\， 但是在通过guacamole连接远程浏览器的时候，打开的是这个路径c:\f2etest\

**Comment by yaniswang** [comment]
是的，这个点忘了在教程中写了，我补一下

**Comment by dail** [comment]
关于第二点，我是拉取了最新代码的。问题出在了nodejs代码中。
f2etest/f2etest-web/control/webdriver.js
在这个文件中的第41行
var program = 'c:\\f2etest\\webdriver\\opennode.bat '+nodeName+'';
此处的路径写成了c:\\f2etest， 而我们文档中的地址是c:\f2etest-webdriver\

**Comment by yaniswang** [comment]
https://github.com/alibaba/f2etest/commit/ee8ccbacb8747aac88a505189e9dffa4d3f3855a

修复了，感谢反馈这个问题
