### ISSUE TITLE
IE 浏览器打开以后默认是禁用Cookie的

### ISSUE THREAD

**Issue by simonguo** [alibaba/f2etest#26]
直接访问这个主机,IE浏览器Cookie默认启用，但是通过f2etest 打开IE浏览器打开以后默认是禁用Cookie的。需要手动修改。  这个可以在哪里配置啊？
我的版本是 V1.0.2 .

**Comment by yaniswang** [comment]
https://github.com/alibaba/f2etest

IE浏览器安全级别低解决方案
