### ISSUE TITLE
按教程安装完出现Some account initialize failed: x.x.x.1

### ISSUE THREAD

**Issue by benjaken** [alibaba/f2etest#29]
打开127.0.0.1:8080 后出现 Some account initialize failed: x.x.x.1

**Comment by qianlx** [comment]
你没配置/f2etest/f2etest-web/conf/server.conf

**Comment by qianlx** [comment]
我也是刚刚再装这个东西
卡死在最后了

**Comment by benjaken** [comment]
@qianlx thanks
