### ISSUE TITLE
能否提供一个docker镜像

### ISSUE THREAD

**Issue by eqyun** [alibaba/f2etest#3]

**Comment by renaesop** [comment]
这货跑在windows上，怎么docker化……

**Comment by yaniswang** [comment]
windows之外的两个组件，倒是可以尝试docker化

**Comment by mzky** [comment]
现在已经有windows版本的docker了

**Comment by mushimeng** [comment]
window版本的docker 哪儿有下载的

**Comment by Stngle** [comment]
https://alibaba.github.io/f2etest/build/#/artist/f2etest/f2etest-web-install
