### ISSUE TITLE
安装到电脑 （/install）页面中部分URL写死了https

### ISSUE THREAD

**Issue by ilazycat** [alibaba/f2etest#30]
这个页面里的几个 URL输入 链接都是写死了的https，没部署https的站点直接复制上面给的url就会出错。最好改成自动识别的。

**Comment by yaniswang** [comment]
WIN7的remote app桌面，要求必需是HTTPS，如果想要支持这个功能，就必需要部署为HTTPS协议。

**Comment by yaniswang** [comment]
已经添加部署说明，感谢反馈
