### ISSUE TITLE
配置webdriver云建议在opennode.bat中增加端口号配置项

### ISSUE THREAD

**Issue by gujiangfei1221** [alibaba/f2etest#35]
部署webdriver云过程发现一直提示“Report to f2etest failed!”，然后反复检查配置和尝试多次，最终发现在wdproxy.js中会对web主机发起一个http请求，默认端口是80，但是我配置浏览器云的端口是3000（没有使用nginx做反向代理），导致我这边提示“Report to f2etest failed!”

所以建议大神在配置文件中加入端口号。

**Comment by yaniswang** [comment]
https://github.com/alibaba/f2etest/blob/master/INSTALL.md

我已经将80反向3000，配置为默认了流程了。

没有80，使用起来太不方便了。
