### ISSUE TITLE
使用该框架如何配置能使得上传文件到windows服务器，并且知道文件上传到windows服务器上的的什么位置了

### ISSUE THREAD

**Issue by zhangjianpinghik** [alibaba/f2etest#37]

**Comment by yaniswang** [comment]
https://github.com/alibaba/f2etest/blob/master/f2etest-guacamole/Install.md

`/home/guacdshare`目录就是用来临时存储上传和下载文件的，详细在f2etest-web的帮助页面里有。

**Comment by zhangjianpinghik** [comment]
@yaniswang  现在我可以上传文件，但是在被远程的windows服务器上看不到想guacamole所说的一个名为G guacamole RDP system folder的虚拟机磁盘驱动，
我的guacamole的配置文件中也设置了相关的参数：
<param name="enable-drive" value="true" />
<param name="drive-path" value="/home/guacdshare" />

**Comment by zhangjianpinghik** [comment]
<param name="enable-drive" value="true" />
        <param name="drive-path" value="/home/guacdshare" />

**Comment by zhangjianpinghik** [comment]
@yaniswang  现在我可以上传文件，但是在被远程的windows服务器上看不到想guacamole所说的一个名为G guacamole RDP system folder的虚拟机磁盘驱动，
我的guacamole的配置文件中也设置了相关的参数
enable-drive和drive-path

**Comment by yaniswang** [comment]
很可能guacamole的插件你没安装好

你看下这几条命令是不是安装正确：yum install cairo-devel libpng-devel uuid-devel freerdp* libvncserver-devel openssl-devel

还有，就是你的操作系统确认是centos 6.x吗？

别的操作系统我没测试过，不保证能用

**Comment by zhangjianpinghik** [comment]
@yaniswang 上述那些库我都安装了的，按说这个功能是guacamole自己的功能，你用在f2etest上的guacamole没有对这一块定制过吧？我的guacamole是安装在ubuntu下的,guacamole对于ubuntu是支持的

**Comment by yaniswang** [comment]
这部分功能就是默认的，没定制过。

ubuntu上我没测试过，不保证就能正常。
