### ISSUE TITLE
这解决方案是面向组织的还是个人的？

### ISSUE THREAD

**Issue by ystyle** [alibaba/f2etest#4]
是不是服务器的机子必需要装上对应IE版本
才能测试?
在一台电脑上能搭建起来么。

**Comment by yaniswang** [comment]
这个解决方案是利用Windows Server的多用户特性，实现的面向团队的高并发多浏览器测试解决方案。

可以在公司内部搭建出一个公用的多浏览器测试环境，并且相互之间有独立的hosts绑定。
