### ISSUE TITLE
IE 浏览器的上下滑动会有问题

### ISSUE THREAD

**Issue by harter123** [alibaba/f2etest#41]
再chrome上面录制的步骤中存在下滑的操作
（it('scrollTo: 0, 807', async function(){
        await driver.scrollTo(0, 807);
    });），但是在ie浏览器回放的时候，ie浏览器下滑到位置后，立刻跳回到顶部

**Comment by yaniswang** [comment]
这个问题我们没有办法解决，这是ie的webdriver驱动有缺陷，如果真想解决，可以考虑提缺陷给iedriver的开发团队
