### ISSUE TITLE
webdriver能支持safari浏览器吗

### ISSUE THREAD

**Issue by harter123** [alibaba/f2etest#42]
我在浏览器云里面可正常配置safari，但是配置webdriver是失败的，有没有支持这个浏览器

**Comment by yaniswang** [comment]
有safaridriver，https://github.com/SeleniumHQ/selenium/wiki/SafariDriver
不过我具体没有测试过。

**Comment by harter123** [comment]
按照教程上的win2008的配置方式是无法支持，只能够是单机版上执行了是吗

**Comment by yaniswang** [comment]
safari没有windows版本，怎么在2008上安装啊？

safari只能在mac上跑
