### ISSUE TITLE
浏览器云不能注销登录,怎么添加自定义的用户

### ISSUE THREAD

**Issue by ElvisTan** [alibaba/f2etest#43]
浏览器云不能注销登录,怎么添加自定义的用户,每次打开就自动登录 了,怎么设置账户

**Comment by yaniswang** [comment]
账户是在用户首次激活时，自动同步到所有windows机器上了

**Comment by Stngle** [comment]
参考文档：https://alibaba.github.io/f2etest/build/#/artist/f2etest/browser-cloud
