### ISSUE TITLE
webdriver云里去掉IE8的配置后，IE11的节点展示问题

### ISSUE THREAD

**Issue by loginXin** [alibaba/f2etest#45]
将IE8的配置从/etc/guacamole/noauth-config.xml和app.json、server.json几个文件中全部删掉，获取的节点的状态错位了（ie11/chrome/firefox配置在一个windows server虚拟机上，且每个虚拟机都配置了3个node）,ie8亮的那两个节点应该是ie11的:
![image](https://user-images.githubusercontent.com/29697328/29200371-5c21e328-7e87-11e7-8bdc-c5c60d71571e.png)

**Comment by yaniswang** [comment]
节点是保存在数据库里的，你要清理节点，需要删除数据库里的记录，改app.json, server.json是没用的，这两个文件是用来配置多浏览器云的。
