### ISSUE TITLE
在使用IE10有时会被卡死，然后注销后再登录，发现原来的访问地址不能访问？

### ISSUE THREAD

**Issue by Automark** [alibaba/f2etest#46]
目前的解决办法是删除该服务器上的用户，然后调用同步接口，这样该用户登录就可以访问了，但是一旦注销后，再重新连接就又出现这个问题

**Comment by Stngle** [comment]
检查 user group 上 user 是否设置成功，更多浏览器云部署方案参考：https://alibaba.github.io/f2etest/build/#/artist/f2etest/browser-cloud-install
