### ISSUE TITLE
UC浏览器：您的链接不是私密链接

### ISSUE THREAD

**Issue by huanhuan129129** [alibaba/f2etest#48]
UC浏览器打开时，一直提示：您的链接不是私密链接
按照网上说的，下载证书， 上传证书也都不管用。

![image](https://user-images.githubusercontent.com/13194743/33008122-c0add5de-ce0c-11e7-814f-21dc4d2f724c.png)

**Comment by Stngle** [comment]
这个应该是浏览器本身的问题
