### ISSUE TITLE
WebDriver浏览器列表显示浏览器个数，怎么控制

### ISSUE THREAD

**Issue by ElvisTan** [alibaba/f2etest#50]
WebDriver浏览器列表显示浏览器个数，怎么控制，比如在win2008安装了360浏览器，和ie8，部署了4个节点，在WebDriver浏览器列表 360浏览器和ie8各显示几个

**Comment by yaniswang** [comment]
各显示4个，这4个是共享一个节点的，虽然共8个，但是并发只能4个

**Comment by chendp111** [comment]
我设置了4个节点，ie8 显示了4个，360只显示了两个。你好能留个其他的联系方式咨询下吗，我的Q373686901

**Comment by Stngle** [comment]
节点展示数据是跟数据库同步的，可以检查一下数据库数据情况。详细的webdriver云部署文档参考：https://alibaba.github.io/f2etest/build/#/artist/f2etest/webdriver-cloud-install
