### ISSUE TITLE
chrome运行uirecorder的用例报错，是哪里没配对么？

### ISSUE THREAD

**Issue by luoxi001713** [alibaba/f2etest#53]
用uirecorder安装的webdriver没问题，但是使用f2etest不行，报如下错误，是哪里没配对么？

`  1) sample/test.spec : chrome "before all" hook:
     Error: the string "unknown error: cannot get automation extension\nfrom unk
nown error: page could not be found: chrome-extension://aapnijgdinlhnhlmodcfapna
hmbfebeb/_generated_background_page.html\n  (Session info: chrome=63.0.3239.108)
\n  (Driver info: chromedriver=2.27.440174 (e97a722caafc2d3a8b807ee115bfb307f7d2
cfd9),platform=Windows NT 6.1.7601 SP1 x86_64) (WARNING: The server did not prov
ide any stacktrace information)\nCommand duration or timeout: 10.10 seconds\nBui
ld info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'\nSy
stem info: host: 'WIN-MCAIGFMMR36', ip: '192.168.201.1', os.name: 'Windows Server
 2008 R2', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_144'\nDriver
info: org.openqa.selenium.chrome.ChromeDriver\nCapabilities [{applicationCacheEn
abled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEna
bled=false, chrome={chromedriverVersion=2.27.440174 (e97a722caafc2d3a8b807ee115b
fb307f7d2cfd9), userDataDir=C:\\Users\\node01\\AppData\\Local\\Temp\\2\\scoped_d
ir7564_26182}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=
false, handlesAlerts=true, hasTouchScreen=false, version=63.0.3239.108, platform
=XP, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, loc
ationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScree
nshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBeh
aviour=}]\nSession ID: 0375186e8aa0ae8e80c5a6333111121221" was thrown, throw an Er
ror :)`

**Comment by yaniswang** [comment]
你的chromedriver版本太老了，不支持chrome 63

**Comment by luoxi001713** [comment]
@yaniswang 那是替换chromedriver.exe还是 还是替换standalone，奇怪，我用f2etest上的jwebdriver的例子就可以，但是使用自己录制的case就不行

**Comment by luoxi001713** [comment]
更新了chromedriver.exe 可以了，非常感谢
