### ISSUE TITLE
能指定在每台机器上跑几个节点么？

### ISSUE THREAD

**Issue by luoxi001713** [alibaba/f2etest#61]
比如我有2台机器，一台10个节点，一共20个节点。
我想10个并发执行，希望在每台机器上跑5个。

**Comment by yaniswang** [comment]
目前是20个节点随机跑，理论上会平均分布在这2台机器上

**Comment by luoxi001713** [comment]
@yaniswang 我看有个绑定hosts，不知道那个怎么用，是不是能实现这个需求？

**Comment by yaniswang** [comment]
这个和hosts绑定有什么关系？
