### ISSUE TITLE
部署webdriver云，没有启动selenium server

### ISSUE THREAD

**Issue by pitter2007** [alibaba/f2etest#62]
执行openallnode.bat时一直提示这个。怎么解
open C:\f2etest-webdriver\rdp\node01.rdp
Node watcher started!
Old mstsc killed!
node01 reopen successed!
Old mstsc killed!
node01 reopen successed!
Old mstsc killed!
node01 reopen successed!
Old mstsc killed!
node01 reopen successed!
Old mstsc killed!
node01 reopen successed!
Old mstsc killed!

**Comment by zhangjian2xxx** [comment]
请问你解决了么？

**Comment by Stngle** [comment]
参考文档：https://alibaba.github.io/f2etest/build/#/artist/f2etest/webdriver-cloud-install
