### ISSUE TITLE
Windows server多用户连接如何突破120天的license限制？

### ISSUE THREAD

**Issue by zhangjingcan** [alibaba/f2etest#63]
如下是官方文档，正常情况下，Windows server最多允许2个用户同时登陆；
https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc725933(v=ws.11)

配置了RDS CALs后，宽限期最多120天。

f2etest可以突破这个限制吗，还是必须要花钱购买这个license？

**Comment by yaniswang** [comment]
安装远程授权服务器就可以：http://blog.csdn.net/hero_cheng/article/details/53486837

**Comment by zhangjingcan** [comment]
按指导配置成功，感谢yaniswang ！
