### ISSUE TITLE
用Chrome访问F2etest成功后，过段就不能访问，换浏览器访问就能进去

### ISSUE THREAD

**Issue by yangdongxu1** [alibaba/f2etest#64]
首先保证：guacamole，f2etest,windows 2008  所以环境都配置正确。能正常访问。
出现一个问题：就是先用chrome访问 配置好的浏览器，访问成功，但不知道什么情况chrome能访问F2etest但是不能远程连接浏览器。换个ie浏览器访问地址，能成功。请问这是怎么回事。

**Comment by Stngle** [comment]
参考文档：https://alibaba.github.io/f2etest/build/#/artist/f2etest/intro
