### ISSUE TITLE
F2etest初始化用户，用户名是随机生成，密码是什么

### ISSUE THREAD

**Issue by yangdongxu1** [alibaba/f2etest#65]
初始化成功后，远程访问浏览器，一进去就提示用户名或密码错误。但我又不知道这个初始化用户的密码、 要么切换administrator登录，要么在windows 2008 里面将用户的密码强制修改进入。。
但是改了之后 首先第一步进去还是提示用户名密码错误。手动输入更改后的密码就可以进入。

**Comment by yaniswang** [comment]
随机密码，可以到数据库里查

**Comment by yaniswang** [comment]
你是不是账号初始化后，又新添加了机器？如果是中途添加的新机器，要执行/syncAllRemoteUsers命令
