### ISSUE TITLE
初始化失败

### ISSUE THREAD

**Issue by wyl316430** [alibaba/f2etest#66]
初始化失败，请联系管理员，错误信息：

Some account initialize failed: x.x.x.1

TypeError: Cannot read property 'ip' of undefined

**Comment by Chorola** [comment]
检查下/f2etest-web/conf/server.json里面的ip是否少了ip字段，正常应该类似如下：
[
    {
        "id": "f2etest-ie8",
        **"ip": "xxx.xxx.xxx.xxx",**
        "remoteApp": true
    }
]

**Comment by Stngle** [comment]
参考文档：https://alibaba.github.io/f2etest/build/#/artist/f2etest/f2etest-web-install
