### ISSUE TITLE
两个节点正常连接，但是selenium server没有启动。

### ISSUE THREAD

**Issue by zhangjian2xxx** [alibaba/f2etest#70]
![image](https://user-images.githubusercontent.com/41861232/44629120-0aae4780-a97d-11e8-8f24-6b5dc450f62f.png)

**Comment by yaniswang** [comment]
安装步骤没有正确执行。
所有账号没初始化的情况下，你就执行了初始化节点的操作
或者你没有初始化节点。

**Comment by yaniswang** [comment]
![image](https://user-images.githubusercontent.com/970390/44644308-3590ae00-aa06-11e8-94b0-325453c4a4e3.png)

必需第2步完成后，才能操作第3步

**Comment by undead25** [comment]
@zhangjian2xxx ，这个呢？

**Comment by Stngle** [comment]
参考文档：https://alibaba.github.io/f2etest/build/#/artist/f2etest/webdriver-cloud-install
