### ISSUE TITLE
点击浏览器云后，服务器拒绝访问。

### ISSUE THREAD

**Issue by zhangjian2xxx** [alibaba/f2etest#71]
![image](https://user-images.githubusercontent.com/41861232/44629308-dab47380-a97f-11e8-90e4-e037e56a830b.png)
![image](https://user-images.githubusercontent.com/41861232/44629315-ed2ead00-a97f-11e8-800f-08c1ed5a7219.png)

**Comment by yaniswang** [comment]
你先试下百度能不能访问

**Comment by undead25** [comment]
这个问题解决了吗？

**Comment by Stngle** [comment]
参考文档：https://alibaba.github.io/f2etest/build/#/artist/f2etest/intro
