### ISSUE TITLE
服务端无法访问clientapi，提示404

### ISSUE THREAD

**Issue by EshineFu** [alibaba/f2etest#72]

**Comment by EshineFu** [comment]
![image](https://user-images.githubusercontent.com/37437935/51165793-589bfb80-18dc-11e9-9277-612c675af1fe.png)

**Comment by undead25** [comment]
可以简单描述下操作流程吗？

**Comment by Stngle** [comment]
参考文档：https://alibaba.github.io/f2etest/build/#/artist/f2etest/intro
