### ISSUE TITLE
windows10 系统+Linux可以搭建成功吗？

### ISSUE THREAD

**Issue by qingranfjj** [alibaba/f2etest#74]
看到环境安装就有点退却啊，没有windows server 2008，只有一台win10+若干Linux服务器，不知道硬件条件符不符合

**Comment by undead25** [comment]
这个要看你的测试目标浏览器了，如果你要测试IE，那就需要有对应的 windows server，里面预装了对应版本的IE。linux 只要一台就可以了，需要有 window server。 win 10 不行。
