### ISSUE TITLE
关于数据库建立和配置的问题

### ISSUE THREAD

**Issue by xuzhitong89** [alibaba/f2etest#8]
1、f2etest.sql，SQL有问题，在创建appUsers，没有创建字段就添加索引了，引起报错，
2、还有您说建一个F2etest表，但是这个SQL是建appLogs，appUsers，也没有这个F2etest表，
3、在配置vi site.json   中"dbTable": "f2etest",不能这样填写吧。
SET FOREIGN_KE"port": 3000,
    "name": "F2eTest",
    "about": "浏览器云测平台",
    "icon": "/favicon.ico",
    "dbHost": "localhost",
    "dbUser": "xxx",
    "dbPass": "xxx",
    "dbTable": "f2etest",
    "clientApiKey":"xxxx",
    "guacamoleApi": "http://f2etest-link.xxxx.com/guacamole/client.xhtml",
    "footer": "",
    "statNav" : "<a href=\"/stat\">标准统计</a> | <a href=\"/statuser\">个人统计</a>"Y_CHECKS=0;

**Comment by yaniswang** [comment]
sql初始化脚本已经修复了，请再试下。

那个新建表是写错了，应该是新建库：f2etest
