### ISSUE TITLE
是否有升级Guacamole的计划?

### ISSUE THREAD

**Issue by qivhou** [alibaba/f2etest#83]
请问是否有升级Guacamole的计划，目前Guacamole已经发布1.0.0正式版，master分支版本还未0.9.3，是否提供升级指南？

**Comment by undead25** [comment]
有这样的打算，不过优先级没有那么高。目前主要集中在优化部署（Docker 及阿里云镜像市场）和文档（估计4月初能审核完发布），后面会对 Web 进行重构，然后可能再投入到升级的工作上去。

**Comment by undead25** [comment]
@qivhou 是否有兴趣参与贡献？

**Comment by qivhou** [comment]
可以参与

**Comment by undead25** [comment]
@qivhou 钉钉群号：21913390
