### ISSUE TITLE
怎样支持edge浏览器？

### ISSUE THREAD

**Issue by 1191685060** [alibaba/f2etest#84]

**Comment by undead25** [comment]
不支持，因为 Window Server 不支持 Edge。

[官方说明]
"The Long-Term Servicing Branch (LTSB) versions of Windows, including Windows Server 2016, don't include Microsoft Edge or many other Universal Windows Platform (UWP) apps. These apps and their services are frequently updated with new functionality, and can't be supported on systems running the LTSB operating systems."

**Comment by Stngle** [comment]
可以尝试 windows10 搭建 edge

**Comment by undead25** [comment]
部署参考链接：https://www.yuque.com/artist/f2etest_blog/audiid
