### ISSUE TITLE
关于sso.js如何实现标准化接入

### ISSUE THREAD

**Issue by yaniswang** [alibaba/f2etest#9]
大家可以在这里一起讨论下如何让sso.js能够参数化接搏各家公司内部的SSO系统，而不是像现在这样需要人肉的修改sso.js。

**Comment by huyinghuan** [comment]
在尝试部署测试过程中，我觉得应该可以允许禁掉sso对接．．．

**Comment by yaniswang** [comment]
如果要禁掉SSO，那么这套系统就必需内建一套账号系统，或者允许匿名使用

**Comment by huyinghuan** [comment]
通过修改sso.js
![image](https://cloud.githubusercontent.com/assets/3005433/11330988/69b69410-91ef-11e5-8647-1b76a6caeed8.png)

这样是否就可以绕过验证了？　因为没有仔细读源码，是否还有需要修改的地方？

**Comment by yaniswang** [comment]
不行，必需要有访问者的用户名和姓名。
用户名是用来和windows集群同步账号的，姓名是用来显示当前你是谁的。

**Comment by huyinghuan** [comment]
那是否可以通过手动写入数据到session来绕开它？

PS 这个东西应该做个可配置就方便了，毕竟不是每个公司都有这样的安全需要，　比如用一个配置较好的服务器拖Ｎ个虚拟机来耍．这些虚拟机就只做测试使用．

**Comment by yaniswang** [comment]
可以考虑下一个版本，做一个匿名访问版本的。
把临时用户名写在cookie里，如果cookie是空的，就生成一个新的临时用户名，如果有了，就用这个用户名访问。

**Comment by yaniswang** [comment]
不过我更建议是能对接到SSO上，这样可以统计用户的使用数据，哪些用户激活了，哪些没使用过。

**Comment by yaniswang** [comment]
改为默认使用内置的匿名SSO：https://github.com/alibaba/f2etest/commit/e0a777787335c5b1b80b154536a842a53f5563ca
