### ISSUE TITLE
测试页面因为浏览器无登录状态，每次都打开需要重新到登录页面登录，登录又停留在人机验证

### ISSUE THREAD

**Issue by qq937654393** [alibaba/f2etest#97]
测试页面因为浏览器无登录状态，每次都打开需要重新到登录页面登录，登录又停留在人机验证，有什么解决方案吗

**Comment by Stngle** [comment]
具体场景是怎样的？有具体截图/描述吗？

**Comment by qq937654393** [comment]
正常录制脚本输入url跳到要测试的业务页面，但是到业务页面因未登录不能访问跳到登录页面。
录制登录操作会出现滑图验证码，无法通过。

**Comment by 3144234615** [comment]
可以使用token进入登陆状态

**Comment by qq937654393** [comment]
刚查了下，比较简单的办法是让后台不要给测试白名单账号做人机校验。

**Comment by undead25** [comment]
是的，人机校验是要需要处理自动化测试的情况，不属于框架需要去解决的。账号白名单或者 IP 白名单都是比较快速解决的一种方式。
